baseurl = "https://www.stomperusa.com/"
title = "exploRations in R"
author = "stomperusa"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = "explorations-in-r"
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

rssLimit = 1

[params]
  sitename = "exploRations in R"

[permalinks]
    post = "/:year/:month/:day/:slug/"



[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/stomperusa"
    weight = 2
[[menu.main]]
    name = "Rbloggers"
    url = "https://www.r-bloggers.com"
    weight = 5
[[menu.main]]
    name = "RSS"
    url = "/post/index.xml"
    weight = 4