baseurl = "https://www.stomperusa.com/"
title = "exploRations in R"
author = "stomperusa"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

rssLimit = 1

[params]
  sitename = "exploRations"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/stomperusa"
    weight = 2
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/stomperusa"
#    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/public/categories/index.xml"
    weight = 5